{{- if and .Values.agentauth.enabled .Values.agentauth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "atb-agentauth" .Values.agentauth.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "atb.labels" . | indent 4 }}
{{- end }}
