{{- if and .Values.broker.enabled .Values.broker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "atb-broker" .Values.broker.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "atb.labels" . | indent 4 }}
{{- end }}
