{{- if and .Values.opa.enabled .Values.opa.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "atb-opa" .Values.opa.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "atb.labels" . | indent 4 }}
{{- end }}
